openapi: 3.0.0
info:
  title: KC API
  version: 1.0.0
  description: API to get kc_flg.
paths:
  /dev/example:
    post:
      summary: Process stones data
      description: Accepts a set of stone coordinates and returns a status flag.
      operationId: processStones
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                stone0:
                  type: object
                  properties:
                    x:
                      type: integer
                      example: 1
                    y:
                      type: integer
                      example: 0
                  required:
                    - x
                    - y
                stone1:
                  type: object
                  properties:
                    x:
                      type: integer
                      example: 0
                    y:
                      type: integer
                      example: 1
                  required:
                    - x
                    - y
                stone2:
                  type: object
                  properties:
                    x:
                      type: integer
                      example: 2
                    y:
                      type: integer
                      example: 1
                  required:
                    - x
                    - y
                stone3:
                  type: object
                  properties:
                    x:
                      type: integer
                      example: 3
                    y:
                      type: integer
                      example: 2
                  required:
                    - x
                    - y
              required:
                - stone0
                - stone1
                - stone2
                - stone3
            examples:
              通常時（リーチ/積みなし）:
                value:
                  stone0: {x: 1, y: 0}
                  stone1: {x: 0, y: 1}
                  stone2: {x: 2, y: 1}
                  stone3: {x: 3, y: 2}
              リーチ時:
                value:
                  stone0: {x: 0, y: 0}
                  stone1: {x: 0, y: 1}
                  stone2: {x: 1, y: 0}
                  stone3: {x: 2, y: 2}
              積み時:
                value:
                  stone0: {x: 0, y: 0}
                  stone1: {x: 0, y: 1}
                  stone2: {x: 1, y: 0}
                  stone3: {x: 1, y: 1}
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  kc_flg:
                    type: integer
                    example: 0
              examples:
                response1:
                  summary: 通常時（リーチ/積みなし）
                  value:
                    kc_flg: 0
                response2:
                  summary: リーチ時
                  value:
                    kc_flg: 1
                response3:
                  summary: 積み時
                  value:
                    kc_flg: 2
servers:
  - url: https://v2vx0npl3f.execute-api.ap-northeast-1.amazonaws.com
    description: AWS API Gateway endpoint
