AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  MyLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: main.handler
      Runtime: python3.9
      CodeUri: ./
      Policies: AWSLambdaBasicExecutionRole
      Environment:
        Variables:
          TABLE_NAME: MyDynamoDBTable